variables:
  COMPOSER_CACHE_DIR: "/cache/composer"
  COMPOSER_ALLOW_SUPERUSER: "1"
  COMPOSER_NO_INTERACTION: "1"
  COMPOSER_VERSION: "2"

default:
  image: $CI_REGISTRY/x-it-docker/docker-php:8.1-build-stable

stages:
  - build
  - validate
  - lint
  - sca
  - migration
  - test

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

build:
  stage: build
  before_script:
    - composer self-update
    - composer --version
    - php --version
  script:
    - composer install --no-progress
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 1 day
    paths:
      - .Build/

validate:composer:
  stage: validate
  needs:
    - build
  script:
    - composer validate --no-check-lock

validate:required-dependencies:
  stage: validate
  needs:
    - build
  before_script:
    - composer global require maglnet/composer-require-checker
  script:
    - composer require --no-progress --no-plugins apache-solr-for-typo3/solr:"^11.5"
    - composer-require-checker check --config-file dependency-checker.json

validate:unused-dependencies:
  stage: validate
  needs:
    - build
  before_script:
    - composer global require icanhazstring/composer-unused
  script:
    - composer install --no-progress --no-plugins
    - composer-unused

lint:composer:
  stage: lint
  needs:
    - build
  script:
    - composer lint:composer -- --dry-run

lint:editorconfig:
  stage: lint
  needs:
    - build
  script:
    - .Build/bin/ec --git-only

lint:php:
  stage: lint
  needs:
    - build
  script:
    - composer lint:php -- --dry-run

lint:typoscript:
  stage: lint
  needs:
    - build
  script:
    - composer lint:typoscript -- --fail-on-warnings

sca:php:
  stage: sca
  needs:
    - build
  script:
    - mkdir -p .Build/log
    - composer sca:php -- --error-format gitlab > .Build/log/phpstan.json
  artifacts:
    reports:
      codequality: .Build/log/phpstan.json

migration:rector:
  stage: migration
  needs:
    - build
  script:
    - composer migration:rector -- --dry-run

test:
  stage: test
  services:
    - mariadb:10
  needs:
    - job: build
      artifacts: false
  image: $CI_REGISTRY/x-it-docker/docker-php:$PHP_VERSION-build-stable
  variables:
    MYSQL_DATABASE: "typo3"
    MYSQL_ROOT_PASSWORD: "typo3"
    typo3DatabaseHost: "mariadb"
    typo3DatabaseUsername: "root"
    typo3DatabasePassword: $MYSQL_ROOT_PASSWORD
    typo3DatabaseName: $MYSQL_DATABASE
  script:
    - composer update --with=typo3/cms-core:"^${TYPO3_VERSION}" --no-progress
    - composer test
  parallel:
    matrix:
      - PHP_VERSION: ["7.4"]
        TYPO3_VERSION: ["10.4"]
      - PHP_VERSION: ["7.4", "8.0", "8.1", "8.2"]
        TYPO3_VERSION: ["11.5"]

test:coverage:
  stage: test
  services:
    - mariadb:10
  needs:
    - build
  variables:
    MYSQL_DATABASE: "typo3"
    MYSQL_ROOT_PASSWORD: "typo3"
    typo3DatabaseHost: "mariadb"
    typo3DatabaseUsername: "root"
    typo3DatabasePassword: $MYSQL_ROOT_PASSWORD
    typo3DatabaseName: $MYSQL_DATABASE
  script:
    - composer test:ci -- --colors=never
    - composer test:ci:merge
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  artifacts:
    reports:
      junit:
        - .Build/log/coverage/junit/functional.xml
        - .Build/log/coverage/junit/unit.xml
      coverage_report:
        coverage_format: cobertura
        path: .Build/log/coverage/cobertura.xml
