variables:
  COMPOSER_CACHE_DIR: "/cache/composer"
  COMPOSER_ALLOW_SUPERUSER: "1"
  COMPOSER_NO_INTERACTION: "1"
  COMPOSER_VERSION: "2"

default:
  image: $CI_REGISTRY/x-it-docker/docker-php:8.0-build-stable

stages:
  - build
  - validate
  - lint
  - sca
  - test

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

build:
  stage: build
  before_script:
    - composer self-update
    - composer --version
    - php --version
  script:
    - composer install --no-progress
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 1 day
    paths:
      - .Build/

.validate-template:
  stage: validate
  needs:
    - build
  before_script:
    - composer global config bin-dir /usr/local/bin

validate:composer:
  extends: .validate-template
  script:
    - composer validate --no-check-lock

validate:required-dependencies:
  extends: .validate-template
  script:
    - composer global require maglnet/composer-require-checker
    - composer require --no-progress --no-plugins apache-solr-for-typo3/solr:"^11.5@RC"
    - composer-require-checker check --config-file dependency-checker.json

validate:unused-dependencies:
  extends: .validate-template
  script:
    - composer global require icanhazstring/composer-unused
    - composer install --no-progress --no-plugins
    - composer-unused

lint:composer:
  stage: lint
  needs:
    - build
  script:
    - composer lint:composer -- --dry-run

lint:editorconfig:
  stage: lint
  needs:
    - build
  script:
    - .Build/bin/ec --git-only

lint:php:
  stage: lint
  needs:
    - build
  script:
    - composer lint:php -- --dry-run

lint:typoscript:
  stage: lint
  needs:
    - build
  script:
    - composer lint:typoscript -- --fail-on-warnings

sca:php:
  stage: sca
  needs:
    - build
  script:
    - mkdir -p .Build/log
    - composer sca:php -- --error-format gitlab > .Build/log/phpstan.json
  artifacts:
    reports:
      codequality: .Build/log/phpstan.json

test:
  stage: test
  services:
    - mariadb:10
  needs:
    - build
  variables:
    MYSQL_DATABASE: "typo3"
    MYSQL_ROOT_PASSWORD: "typo3"
    typo3DatabaseHost: "mariadb"
    typo3DatabaseUsername: "root"
    typo3DatabasePassword: $MYSQL_ROOT_PASSWORD
    typo3DatabaseName: $MYSQL_DATABASE
  script:
    - composer test:ci -- --testdox
    - composer test:ci:merge
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  artifacts:
    reports:
      junit:
        - .Build/log/coverage/junit/functional.xml
        - .Build/log/coverage/junit/unit.xml
