services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Fr\Typo3HandlebarsComponents\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/DependencyInjection/*'
