services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Fr\Typo3HandlebarsComponents\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/DependencyInjection/*'

  Fr\Typo3HandlebarsComponents\Pagination\Linker\PaginationLinkerInterface:
    alias: 'Fr\Typo3HandlebarsComponents\Pagination\Linker\DefaultPaginationLinker'
