services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cpsit\Typo3HandlebarsComponents\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/DependencyInjection/*'

  Cpsit\Typo3HandlebarsComponents\Pagination\Linker\PaginationLinkerInterface:
    alias: 'Cpsit\Typo3HandlebarsComponents\Pagination\Linker\DefaultPaginationLinker'

  Cpsit\Typo3HandlebarsComponents\Data\MediaProvider:
    public: true
  Cpsit\Typo3HandlebarsComponents\Presenter\VariablesResolver\MediaVariablesResolver:
    public: true
